package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entities.User;
import model.DBUtilEventType;
import model.DBUtilRoute;
import model.DBUtilEvent;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles_user.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles_overlay.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/basic.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/toolbarStyle.css\" />\r\n");
      out.write(" \r\n");
      out.write("<!-- =============================== Google Map Scripts =============================== -->\r\n");
      out.write('\r');
      out.write('\n');
 if( request.getLocalAddr().equals("158.130.6.223") ) { 
      out.write("\r\n");
      out.write("<script src=\"http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAiUy24FJ2pI4aK2GRl7uYJRRyJaKxKEBa7ZCCRoWpGBgWzNSuoBTM3814vdtXsPWQBBJcr7o22Ufqfw\" \r\n");
      out.write("        type=\"text/javascript\"></script>\r\n");
 } else { 
      out.write("\r\n");
      out.write("<script src=\"http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAwNRsCttn_9209vEUNVvtyxT2yXp_ZAY8_ufC3CFXhHIE1NvwkxQkSsxzavUfI4qYgHd_KyuAMbdCzQ\" \r\n");
      out.write("        type=\"text/javascript\"></script>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Combo-handled YUI CSS files: -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://yui.yahooapis.com/combo?2.6.0/build/reset-fonts-grids/reset-fonts-grids.css&2.6.0/build/assets/skins/sam/skin.css\">\r\n");
      out.write("<!-- Combo-handled YUI JS files: -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://yui.yahooapis.com/combo?2.6.0/build/utilities/utilities.js&2.6.0/build/container/container-min.js&2.6.0/build/menu/menu-min.js&2.6.0/build/button/button-min.js&2.6.0/build/calendar/calendar-min.js&2.6.0/build/slider/slider-min.js&2.6.0/build/colorpicker/colorpicker-min.js&2.6.0/build/json/json-min.js&2.6.0/build/layout/layout-min.js&2.6.0/build/paginator/paginator-min.js&2.6.0/build/tabview/tabview-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--  ================================= Custom CSS to override YUI CSS style ========== -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/calendar.css\" />\r\n");
      out.write("\r\n");
      out.write("<!--  ================================= Custom Scripts ================================ -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/map.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/floatingToolbar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/leftToolbar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/login.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/search.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/myaccount.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/accordion-menu-v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Penn Fitness</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<body class=\" yui-skin-sam\"> \r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div class=\"archHeader\">\r\n");
      out.write("        <table class=\"top\">\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td class=\"im\"><a class=\"image\" href=\"http://spam.seas.upenn.edu/home/index.htm\">\r\n");
      out.write("            <img src=\"assets/spamlogo.png\" alt=\"SPAM Home\"/></a>\r\n");
      out.write("            </td>\r\n");
      out.write("          \r\n");
      out.write("            <td class=\"appname\" align=\"center\" valign=\"middle\">Penn Fitness</td>\r\n");
      out.write("              \r\n");
      out.write("            <td align=right valign=top class=\"links\"> \r\n");
      out.write("            <a class=\"link\" onmouseover=\"this.className='link2'\" onmouseout=\"this.className='link'\" href=\"http://spam.seas.upenn.edu:8088/Fitness/\"> Penn Fitness </a> | \r\n");
      out.write("            <a class=\"link\" onmouseover=\"this.className='link2'\" onmouseout=\"this.className='link'\" href=\"http://spam.seas.upenn.edu:8088/PennShare\"> Penn CISRS </a> | \r\n");
      out.write("            <a class=\"link\" onmouseover=\"this.className='link2'\" onmouseout=\"this.className='link'\" href=\"http://spam.seas.upenn.edu/~appdev3/\"> Penn Chingu </a> | \r\n");
      out.write("            <a class=\"link\" onmouseover=\"this.className='link2'\" onmouseout=\"this.className='link'\" href=\"http://spam.seas.upenn.edu/home/index.htm\"> Older SPAM </a> \r\n");
      out.write("            </td>\r\n");
      out.write("            </tr>            \r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"topMenuBar\">\r\n");
      out.write("    <!-- Login input or user information -->\r\n");
      out.write("            <span id=\"user\">\r\n");
      out.write("                ");

                User user=(User) session.getAttribute("user");
                if(user == null) {
                    // if not logged in
                
      out.write("\r\n");
      out.write("                username: <input type=\"text\" name=\"userID\" id=\"userID\" size=5 maxlength=\"20\" /> \r\n");
      out.write("                password: <input type=\"password\" name=\"password\" id=\"password\" size=5 maxlength=\"20\" /> \r\n");
      out.write("                <a href=\"javascript:Login()\"/>Login</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:ShowUserRegDialog()\"/>Sign Up!</a>\r\n");
      out.write("                ");

                } // end of if(user == null) 
                else {
                    // if logged in
                
      out.write("\r\n");
      out.write("                Welcome ");
      out.print(user.getUserName() );
      out.write(' ');
      out.write('(');
      out.print(user.getUserID());
      out.write(")!\r\n");
      out.write("                ");
 out.println("<a href=\"javascript:ShowMyAccountDialog('"+user.getUserID()+"')\"/>My Account</a>"); 
      out.write("\r\n");
      out.write("                <a href=\"javascript:createRt()\"/>Create a New Route</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:Logout()\"/>Logout</a>\r\n");
      out.write("                ");
 // end of else
                }
                
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("            <span id=\"showbtns\">\r\n");
      out.write("            \t<a href=\"javascript:ShowSearchDialog()\"/>Search</a>\r\n");
      out.write("                <!--<input type=\"button\" name=\"searchDialogBtn\" id=\"searchDialogBtn\" value=\"Search\" onclick=\"ShowSearchDialog()\"/>\r\n");
      out.write("                 <input type=\"button\" name=\"temp\" id=\"temp\" value=\"Show New\" onclick=\"showNewRtTool()\"/>\r\n");
      out.write("                <input type=\"button\" name=\"temp2\" id=\"temp2\" value=\"Hide New\" onclick=\"hideNewRtTool()\"/> -->\r\n");
      out.write("            </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"archFooter\" class=\"archFooter\">\r\n");
      out.write("        <table class=\"bottom\" >\r\n");
      out.write("        \r\n");
      out.write("        <tr align=\"center\">\r\n");
      out.write("        \r\n");
      out.write("        <td class=\"spacing\" align=\"left\">Copyright (c) System for Penn Active Maps</td>\r\n");
      out.write("        <td></td><td></td>\r\n");
      out.write("        <td align = \"right\">\r\n");
      out.write("        <a class=\"ft\" onmouseover=\"this.className='ft2'\" onmouseout=\"this.className='ft'\" href=\"http://spam.seas.upenn.edu/about\">About</a> | \r\n");
      out.write("        <a class=\"ft\" onmouseover=\"this.className='ft2'\" onmouseout=\"this.className='ft'\" href=\"http://www.upenn.edu/privacy/\">Privacy</a> | \r\n");
      out.write("        <a class=\"ft\" onmouseover=\"this.className='ft2'\" onmouseout=\"this.className='ft'\" href=\"http://www.upenn.edu/about/disclaimer.php\">Disclaimer</a> | \r\n");
      out.write("        <a class=\"ft\" onmouseover=\"this.className='ft2'\" onmouseout=\"this.className='ft'\" href=\"http://www.upenn.edu/\">Penn Home</a> | \r\n");
      out.write("        <a class=\"ft\" onmouseover=\"this.className='ft2'\" onmouseout=\"this.className='ft'\" href=\"http://www.cis.upenn.edu/\">CIS Home</a>\r\n");
      out.write("        </td>\r\n");
      out.write("              \r\n");
      out.write("        </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"centerArea\">\r\n");
      out.write("\t<div id=\"leftMenu\" class=\"leftMenuTitle\">\r\n");
      out.write("        <div id=\"leftEventCalendar\"></div>\r\n");
      out.write("        <input type=\"hidden\" id=\"eventDatesCurrentMonth\" value=\"");
      out.print( DBUtilEvent.getEventDatesForCurMonth() );
      out.write("\" />\r\n");
      out.write("        <dl class=\"accordion-menu\" id=\"my-dl\">\r\n");
      out.write("            <dt class=\"a-m-t\" id=\"my-dt-1\">Events</dt>\r\n");
      out.write("            <input type=\"hidden\" id=\"totalEventCnt\" value=");
      out.print( DBUtilEvent.getAllEventsCount() );
      out.write(" />\r\n");
      out.write("            <dd class=\"a-m-d\">\r\n");
      out.write("                <div class=\"bd\" id=\"evtListSection\">\r\n");
      out.write("                    <div id=\"eventListTabArea\" class=\"yui-navset\">\r\n");
      out.write("                    \t<ul class=\"yui-nav\">\r\n");
      out.write("                        \t<li class=\"selected\"><a href=\"#dateEvtListTab\"><em>By Date</em></a></li>\r\n");
      out.write("                            <li><a href=\"#newEvtListTab\"><em>New</em></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"yui-content\">\r\n");
      out.write("\t                        <div id=\"dateEvtListTab\">\r\n");
      out.write("\t                        \t<div id=\"eventsOnDateList\">\r\n");
      out.write("\t                        \t\t<!-- Shows events on selected date -->\r\n");
      out.write("\t                        \t</div>\r\n");
      out.write("    \t                    \t<div id=\"pag_eventsOnDateList\" class=\"paginator\">\r\n");
      out.write("    \t                    \t\t<!-- paginator -->\r\n");
      out.write("    \t                    \t</div\r\n");
      out.write("\t                        </div>\r\n");
      out.write("    \t                    <div id=\"newEvtListTab\">\r\n");
      out.write("    \t                    \t<div id=\"newEventsList\">\r\n");
      out.write("    \t                    \t\t");
      out.print( DBUtilEvent.getAllEventsHTML(5,1) );
      out.write("\r\n");
      out.write("    \t                    \t</div>\r\n");
      out.write("    \t                    \t<div id=\"pag_newEventsList\" class=\"paginator\">\r\n");
      out.write("    \t                    \t\t<!-- paginator -->\r\n");
      out.write("    \t                    \t</div\r\n");
      out.write("    \t                    </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </dd>  \r\n");
      out.write("            <dt class=\"a-m-t\" id=\"my-dt-2\">Routes</dt>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"totalRouteCnt\" value=");
      out.print( DBUtilRoute.getAllRoutesCount() );
      out.write(" />\r\n");
      out.write("            <dd class=\"a-m-d\">\r\n");
      out.write("                <div class=\"bd\" id=\"rtListSection\">\r\n");
      out.write("                    <div id=\"routeListTabArea\" class=\"yui-navset\">\r\n");
      out.write("\t                    <ul class=\"yui-nav\">\r\n");
      out.write("       \t                   \t<li><a href=\"#popularRtListTab\"><em>Popular</em></a></li>\r\n");
      out.write("                            <li class=\"selected\"><a href=\"#newRtListTab\"><em>New</em></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"yui-content\">\r\n");
      out.write("\t                        <div id=\"popularRtListTab\">\r\n");
      out.write("\t                        \t<div id=\"popularRoutesList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( DBUtilRoute.getPopularRoutesHTML(5, 1) );
      out.write("\r\n");
      out.write("\t                        \t</div>\r\n");
      out.write("\t    \t                    <div id=\"pag_popularRoutesList\" class=\"paginator\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- paginator -->\r\n");
      out.write("\t\t\t                \t</div>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("    \t                    <div id=\"newRtListTab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"newRoutesList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( DBUtilRoute.getAllRoutesHTML(5, 1) );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t    \t                    <div id=\"pag_newRoutesList\" class=\"paginator\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- paginator -->\r\n");
      out.write("\t\t\t                \t</div>\r\n");
      out.write("    \t                    </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("              \t</div>\r\n");
      out.write("            </dd>\r\n");
      out.write("\t    </dl>    \r\n");
      out.write("    </div>\r\n");
      out.write("\t<div id=\"map\">map area</div>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("           <!-- ======================== Floating TOOLBAR:  ===================== -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"floatingToolbar\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- ======================== Route Detail TOOLBAR:  ===================== -->\r\n");
      out.write("        <div class=\"hd\">Route Details</div>\r\n");
      out.write("        <div class=\"bd\">\r\n");
      out.write("            <form name=\"frmRouteDetails\" id=\"frmRouteDetails\" method=\"post\" action=\"#\">\r\n");
      out.write("                <div class=\"generalInfo\" id=\"routeGeneral\">\r\n");
      out.write("                    <span id=\"routeName\">Mai's Route</span> <span id=\"routeCreator\">by need from server</span><br />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"routeNameTxtDiv\">\r\n");
      out.write("                \t<span id=\"routeNameLabel\">Route Name: </span>\r\n");
      out.write("                    <input type=\"text\" name=\"routeName\" id=\"routeNameTxt\" maxlength=\"20\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"routeTimeDist\">\r\n");
      out.write("                \t<span id=\"routeCreatedDate\">created need date from server</span> <span id=\"routeDistance\">(1.5 miles)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ratings\" id=\"rtRatings\">\r\n");
      out.write("                    <span id=\"overallRating\"></span>\r\n");
      out.write("                    <span id=\"sceneryRating\"></span>\r\n");
      out.write("                    <span id=\"difficultyRating\"></span>\r\n");
      out.write("                    <span id=\"safetyRating\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"routeDesc\">\r\n");
      out.write("                    Route Description here...\t  \t\t        \r\n");
      out.write("                </div>\r\n");
      out.write("                <textarea name=\"routeDesc\" id=\"routeDescTxt\" wrap=\"virtual\"></textarea>\r\n");
      out.write("                <div id=\"rtColor-container\">Route Color: </div>\r\n");
      out.write("                <div class=\"toolbarBtns\">\r\n");
      out.write("                    <div id=\"saveRoute\">\r\n");
      out.write("                        <input type=\"button\" id=\"saveRouteBtn\" value=\"Save\" />\r\n");
      out.write("                        <input type=\"button\" id=\"cancelRouteBtn\" value=\"Cancel\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"modifyRoute\">\r\n");
      out.write("                        <input type=\"button\" id=\"modifyRouteBtn\" value=\"Modify\" />    \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"deleteRouteBtn\" value=\"Delete\" />                 \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div id=\"routeEvents\">\r\n");
      out.write("                <span id=\"totalEvents\"></span> \r\n");
      out.write("                <a href=\"javascript:createEvt()\" id=\"newEventLink\"/>New Event</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    <!-- ======================== Event Detail TOOLBAR:  ===================== --> \r\n");
      out.write("                   \r\n");
      out.write("            <div id=\"eventDetails\" style=\"display:none\">\r\n");
      out.write("            \t<hr />\r\n");
      out.write("            \t <div id=\"hideEvtList\"><a href=\"javascript:hideEventList()\">Hide Event List</a></div>\r\n");
      out.write("                 <div class=\"eventHd\">Event List</div>\r\n");
      out.write("                 <div class=\"toolbarPages\" id=\"eventList\">\r\n");
      out.write("                 \t<input type=\"hidden\" id=\"ELBRrecsPerPage\" name=\"recsPerPage\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"ELBRcurPage\" name=\"curPage\" value=\"1\" />\r\n");
      out.write("                 \t<div id=\"eventListByRoute\" class=\"eventList\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"pag_eventsListByRoute\" class=\"paginator\">\r\n");
      out.write("\t\t\t\t\t\t<!-- paginator -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>   \r\n");
      out.write("                <div id=\"specificEvent\" style=\"display:none\">\r\n");
      out.write("                \t<hr />\r\n");
      out.write("                \t <div id=\"hideEvtDetail\" ><a href=\"javascript:displayEventList()\">Back to List</a></span><br /></div>\r\n");
      out.write("\t                 <div class=\"generalInfo\" id=\"eventGeneral\">\r\n");
      out.write("\t                 \t<div class=\"eventHd\">Event Details</div>          \t\r\n");
      out.write("\t                    <span id=\"eventName\">Event Name</span> <span id=\"eventCreator\">by Mai</span><br />\r\n");
      out.write("\t                    <span id=\"eventCreatedDate\">Created on: 11/30/2008</span><br />\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"eventDetails\">\r\n");
      out.write("\t                    <span id=\"eventStart\">1:00 PM</span><span id=\"eventDuration\">(1 hour)</span><br />\r\n");
      out.write("\t                    <span id=\"eventPrivacy\">Public</span> <span id=\"eventType\">Casual Run</span> <span id=\"eventGroup\">Group 1</span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"description\" id=\"eventDesc\">\r\n");
      out.write("\t                    Event Description here...\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"toolbarBtns\">\r\n");
      out.write("\t                    <input type=\"button\" id=\"modifyEventBtn\" value=\"Modify\" />\r\n");
      out.write("\t                    <input type=\"button\" id=\"deleteEventBtn\" value=\"Delete\" />\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>                 \r\n");
      out.write("                            \r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- =================== Event Create/Modify Dialog:  =================== -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"eventDialog\">\r\n");
      out.write("        <div class=\"hd\">Edit Event Details</div>\r\n");
      out.write("        <div class=\"bd\">\r\n");
      out.write("            <form name=\"frmCreateEvent\" id=\"frmCreateEvent\" method=\"post\" action=\"saveEvent.do\">\r\n");
      out.write("                <label for=\"eventNameTxt\">Event Name:</label> <input type=\"text\" name=\"eventName\" id=\"eventNameTxt\" size=\"10\" maxlength=\"30\" /><br />                                \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"publicity\">Publicity:</label>\r\n");
      out.write("                <input type=\"radio\" name=\"publicity\" id=\"publicEvt\" value=\"Y\" checked=\"checked\"/> Public Event\r\n");
      out.write("                <input type=\"radio\" name=\"publicity\" id=\"privateEvt\" value=\"N\" /> Private Event <br />                \r\n");
      out.write("                <label for=\"evtGroup\">Group Name:</label> <select id=\"evtGroup\" name=\"groupID\">\r\n");
      out.write("                    <option value=\"-1\" selected=\"selected\">None</option>\r\n");
      out.write("                </select><br />\r\n");
      out.write("                 <label for=\"evtType\">Event Type:</label><select id=\"evtType\" name=\"eventTypeID\">\r\n");
      out.write("                    <option value=\"-1\" selected=\"selected\">Please select a type</option>\r\n");
      out.write("                    ");
      out.print( DBUtilEventType.getAllEventTypesOptions() );
      out.write("\r\n");
      out.write("                </select><br />                \r\n");
      out.write("                <label for=\"eventTimeStart\">Event Start Time:</label> <select id=\"eventTimeStart\" name=\"eventTimeStart\" ></select>\r\n");
      out.write("                <select name=\"AM_PM\" id=\"AM_PM\">\r\n");
      out.write("                \t<option value=\"AM\" selected=\"selected\">AM</option>\r\n");
      out.write("                \t<option value=\"PM\">PM</option>\r\n");
      out.write("                </select><br />\r\n");
      out.write("                <label for=\"eventDurationTxt\">Duration: (in hours - e.g., 1.5)</label> \r\n");
      out.write("                <input type=\"text\" name=\"eventDuration\" id=\"eventDurationTxt\" size=\"10\" maxlength=\"30\" /><br />\r\n");
      out.write("                <div id=\"date\">\r\n");
      out.write("                    <label for=\"evtCalTxt\">Event Date:</label> <input type=\"text\" name=\"evtCalTxt\" id=\"evtCalTxt\"  size=\"10\" maxlength=\"10\"/>\r\n");
      out.write("                </div><div id=\"buttoncalendar\"></div>                \r\n");
      out.write("                <p>Description:</p>\r\n");
      out.write("                <textarea id=\"eventDescTxt\" name=\"eventDesc\" wrap=\"virtual\"></textarea><br />\r\n");
      out.write("                <input type=\"hidden\" name=\"eventID\" id=\"eventIDTxt\" value=\"-1\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"routeID\" id=\"routeIDTxt\" value=\"-1\"/>\r\n");
      out.write("                <input type=\"hidden\" name=\"eventTime\" id=\"evtStartTxt\" value=\"\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"eventDate\" id=\"evtDateTxt\" value=\"\" />\t\t\t\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- =============================== User Registration DIALOG Structure:  =============================== -->\r\n");
      out.write("    <div id=\"userRegDialog\">\r\n");
      out.write("        <div class=\"hd\">New User Registration</div>\r\n");
      out.write("        <div class=\"bd\">\r\n");
      out.write("            <form method=\"POST\" action=\"registerUser.do\">\r\n");
      out.write("                <label for=\"userName\">Name:</label><input type=\"text\" name=\"userName\" />\r\n");
      out.write("                <label for=\"userID\">User ID:</label><input type=\"text\" name=\"userID\" />\r\n");
      out.write("                <label for=\"password\">Password:</label> <input type=\"password\" name=\"password\" />                    \r\n");
      out.write("                <label for=\"email\">E-mail:</label><input type=\"text\" name=\"email\" /> \r\n");
      out.write("    \r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("    \r\n");
      out.write("                <label for=\"publicNotify\">Notified for public events:</label> <input type=\"checkbox\" name=\"publicNotify\" value=\"Y\" checked/>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("    \r\n");
      out.write("                <label for=\"height\">Height:</label> <input type=\"text\" name=\"height\" />\r\n");
      out.write("                <label for=\"weight\">Weight:</label> <input type=\"text\" name=\"weight\" />\r\n");
      out.write("                    <div class=\"clear\"></div>\r\n");
      out.write("                <label for=\"gender\">Gender:</label>\r\n");
      out.write("                <input type=\"radio\" name=\"gender\" value=\"N\" /> N/A\r\n");
      out.write("                <input type=\"radio\" name=\"gender\" value=\"M\" /> Male\r\n");
      out.write("                <input type=\"radio\" name=\"gender\" value=\"F\" /> Female    \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- =============================== My Account DIALOG Structure:  =============================== -->\r\n");
      out.write("    <div id=\"panel1\">\r\n");
      out.write("        <div id = \"overlayTabOne\" class=\"overlayOne\">\r\n");
      out.write("            <ul class = \"yui-nav\">\r\n");
      out.write("                <li class = \"selected\">\r\n");
      out.write("                    <a href = \"#tab1\"><em>Personal Information</em></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href = \"#tab2\" onclick=\"populateGroupByUserID();\"><em>Group Information</em></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href = \"#tab3\"><em>Event Information</em></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href = \"#tab4\"><em>Route Information</em></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class = \"yui-content\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div id = \"personalInfo\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\t\t\r\n");
      out.write("                <div>\r\n");
      out.write("                        <div id = \"GroupInfoTab\" class=\"GroupInfo\">\r\n");
      out.write("                            <ul class = \"yui-nav\">\r\n");
      out.write("                                <li class = \"selected\">\r\n");
      out.write("                                    <a href = \"#tab1\"><em>My Groups</em></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                \t<a href = \"#tab2\"><em>Created Groups</em></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                \t<a href = \"#tab3\"><em>Create a Group</em></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class = \"yui-content\">\r\n");
      out.write("                                <div class = \"myGroups\">\r\n");
      out.write("                                    <div id=\"myGroupList\">\r\n");
      out.write("                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div id=\"myGroupDetail\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"myGroupsButtons\">\r\n");
      out.write("                                        <input type=\"button\" value=\"Send Emails\" id=\"SendEmails\" />\r\n");
      out.write("                                        <input type=\"button\" value=\"Unsubscribe\" id=\"Unsubscribe\" />\r\n");
      out.write("                                    </div>\t\t\t\t\t\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class = \"createdGroups\">\r\n");
      out.write("                                    <div class=\"createdGroupList\">\r\n");
      out.write("                                        <div class=\"createdGroupItem\">\r\n");
      out.write("                                            <span class=\"number\">1.</span>\r\n");
      out.write("                                            <a href=\"function_to_show_group_detail\">my Created Group 1</a>\r\n");
      out.write("                                            <span class=\"createdDate\">since Nov. 1st, 2008</span>\r\n");
      out.write("                                            <span class=\"memberCount\"># 5</span>\r\n");
      out.write("                                            <p>This is an awesome group where members meet every Wednesday night in front of Towne to start a one hour jogging \r\n");
      out.write("                                                trip</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"createdGroupItem\">\r\n");
      out.write("                                            <span class=\"number\">2.</span>\r\n");
      out.write("                                            <a href=\"function_to_show_group_detail\">my Created Group 2</a>\r\n");
      out.write("                                            <span class=\"createdDate\">since May. 25th, 2009</span>\r\n");
      out.write("                                            <span class=\"memberCount\">#8</span>\r\n");
      out.write("                                            <a href=\"function_to_show_group_detail\">more...</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"myGroupItem\">\r\n");
      out.write("                                            <span class=\"number\">3.</span>\r\n");
      out.write("                                            <a href=\"function_to_show_group_detail\">my Created Group 3</a>\r\n");
      out.write("                                            <span class=\"createdDate\">since Jan. 15th, 2009</span>\r\n");
      out.write("                                            <span class=\"memberCount\"># 15</span>\r\n");
      out.write("                                            <a href=\"function_to_show_group_detail\">more...</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div id=\"buttons\">\r\n");
      out.write("                                        <input type=\"button\" value=\"Send Emails\" id=\"SendEmails\" />\r\n");
      out.write("                                        <input type=\"button\" value=\"Modify\" id=\"Modify\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class = \"createAGroup\">\r\n");
      out.write("                                        <form name=\"frmCreateGroupData\" id=\"frmCreateGroupData\">\r\n");
      out.write("                                        Name <input type=\"text\" name=\"Group Name\" size=\"10\" id=\"groupName\" /><br>\r\n");
      out.write("                                        Description <input type=\"text\" name=\"Description\" size=\"30\" id=\"Description\" /><br>\r\n");
      out.write("                                        <input type=\"button\" name=\"Create\" value=\"Create\" id=\"Create\" /><br>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div id =\"EventInfoTab\" class=\"EventInfo\">\r\n");
      out.write("                        <ul class = \"yui-nav\">\r\n");
      out.write("                            <li class = \"selected\">\r\n");
      out.write("                                <a href = \"#tab1\"><em>Registered Events</em></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href = \"#tab2\"><em>Created Events</em></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class = \"yui-content\">\r\n");
      out.write("                            <div class = \"registeredEvents\">\r\n");
      out.write("                                <div class=\"registeredEventList\">\r\n");
      out.write("                                    <div class=\"registeredEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Inseob Event 007</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"RouteInfoItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Girls go jogging</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"RouteInfoItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sansom E. Halloween jogging</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class = \"createdEvents\">\r\n");
      out.write("                                <div class=\"createdEventList\">\r\n");
      out.write("                                    <div class=\"createdEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sandy Event 1</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"createdEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sandy Event 2</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"createdEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sandy Event 3</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"createdEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sandy Event 4</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"createdEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sandy Event 5</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"createdEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sandy Event 6</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"createdEventItem\">\r\n");
      out.write("                                        <a href=\"function_to_show_event\">Sandy Event 7</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"RouteInfoList\">\r\n");
      out.write("                        <div class=\"RouteInfoItem\">\r\n");
      out.write("                            <a href=\"function_to_show_route\">Difficult Route 001</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"RouteInfoItem\">\r\n");
      out.write("                            <a href=\"function_to_show_route\">Coolest Route Ever</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"RouteInfoItem\">\r\n");
      out.write("                            <a href=\"function_to_show_route\">Sweet Path in Philly</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>                \r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("    <!-- =============================== Search DIALOG Structure:  =============================== -->\t\r\n");
      out.write("    <div id=\"panel2\">\r\n");
      out.write("        <div id = \"overlayTabTwo\" class=\"overlayTwo\">\r\n");
      out.write("            <ul class = \"yui-nav\">\r\n");
      out.write("                <li class = \"selected\">\r\n");
      out.write("                    <a href = \"#tab1\"><em>Event Search</em></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href = \"#tab2\"><em>Group Search</em></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href = \"#tab3\"><em>Route Search</em></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class = \"yui-content\">\r\n");
      out.write("                <div class = \"eventSearch\">\r\n");
      out.write("                    <form name=\"frmEventSearchData\" id=\"frmEventSearchData\">\r\n");
      out.write("                    \tKeyword :<input type=\"text\" size=10 name=\"keyword\" id=\"ESKeyword\" />&nbsp;&nbsp;\r\n");
      out.write("                    \t<label for=\"evtType\">Event Type:</label><select id=\"ESevtType\" name=\"type\">\r\n");
      out.write("                    \t<option value=\"\" selected=\"selected\">All types</option>\r\n");
      out.write("                  \t\t  ");
      out.print( DBUtilEventType.getAllEventTypesOptions() );
      out.write("\r\n");
      out.write("                \t\t</select><br />\r\n");
      out.write("                    \tDate :<input type=\"text\" size=10 maxlength=10 name=\"fromDate\" id=\"ESFromDate\" />\r\n");
      out.write("                    \t\t  <input type=\"text\" size=10 maxlength=10 name=\"toDate\" id=\"ESToDate\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"Search\" onclick=\"searchEvent()\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"ESrecsPerPage\" name=\"recsPerPage\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"EScurPage\" name=\"curPage\" value=\"1\" />\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <div id=\"eventSearchResult\" class=\"Result\">\r\n");
      out.write("                    \t<!-- group search result -->\r\n");
      out.write("                    </div>\r\n");
      out.write("\t                <div id=\"pag_eventSearchResult\" class=\"paginator\">\r\n");
      out.write("\t\t\t\t\t\t<!-- paginator -->\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class = \"groupSearch\">\r\n");
      out.write("                        <form name=\"frmGroupSearchData\" id=\"frmGroupSearchData\">\r\n");
      out.write("\t                    \tKeyword :<input type=\"text\" size=10 name=\"keyword\" id=\"GSKeyword\" />&nbsp;&nbsp;\r\n");
      out.write("\t                    \tCreator ID :<input type=\"text\" size=10 name=\"creatorID\" id=\"GSCreator\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"Search\" onclick=\"searchGroup()\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"GSrecsPerPage\" name=\"recsPerPage\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"GScurPage\" name=\"curPage\" value=\"1\" />\r\n");
      out.write("                        </form>\r\n");
      out.write("\t                    <br />\r\n");
      out.write("                        <div id=\"groupSearchResult\" class=\"Result\">\r\n");
      out.write("                        \t<!-- group search result -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t                <div id=\"pag_groupSearchResult\" class=\"paginator\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- paginator -->\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class = \"routeSearch\">\t\r\n");
      out.write("                        <form name=\"frmRouteSearchData\" id=\"frmRouteSearchData\">\r\n");
      out.write("\t                    \tKeyword :<input type=\"text\" size=10 name=\"keyword\" id=\"RSKeyword\" />&nbsp;&nbsp;\r\n");
      out.write("\t                    \tDistance :<input type=\"text\" size=3 maxlength=3 name=\"fromDistance\" id=\"RSFromDistance\" />~\r\n");
      out.write("\t                    \t\t\t  <input type=\"text\" size=3 maxlength=3 name=\"toDistance\" id=\"RSToDistance\" /><br />\r\n");
      out.write("\t                    \tDate :<input type=\"text\" size=10 maxlength=10 name=\"fromDate\" id=\"RSFromDate\" />\r\n");
      out.write("\t                    \t\t  <input type=\"text\" size=10 maxlength=10 name=\"toDate\" id=\"RSToDate\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"Search\" onclick=\"searchRoute()\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"RSrecsPerPage\" name=\"recsPerPage\"  />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"RScurPage\" name=\"curPage\" value=\"1\" />\r\n");
      out.write("\t                    <br />\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div id=\"routeSearchResult\" class = \"Result\">\r\n");
      out.write("                        \t<!-- route search result -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t                <div id=\"pag_routeSearchResult\" class=\"paginator\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- paginator -->\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>  \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
